#!/bin/bash

WOFI="wofi --show=dmenu"

# Menu items
items="restart
logout
hibernate
suspend
poweroff"

# Open menu
selection=$(printf '%s' "$items" | $WOFI)

case $selection in
	restart)
		systemctl reboot
		;;
	logout)
		hyprctl dispatch exit
		;;
	hibernate)
		systemctl hibernate
		;;
	suspend)
		systemctl suspend
		;;
	halt|poweroff|shutdown)
		systemctl poweroff
		;;
esac
