#!/usr/bin/env bash

function run {
  if ! pgrep -f $1 ;
  then
    $@&
  fi
}

run setxkbmap -layout de -option compose:prsc
run mpd
run /usr/bin/lxqt-policykit-agent 
run nm-applet 
run picom 
(sleep 1s && run pasystray) 
(sleep 4s && run parcellite) 
(sleep 5s && run dropbox) 
